pool:
  vmImage: 'ubuntu-latest'

name: $(Build.BuildId)

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
      - azure-pipelines-deploy.yml

resources:
  repositories:
    - repository: sd4780_msa
      type: git
      name: 'sd4780-devops/sd4780_msa'
      ref: main
      trigger:
        branches:
          include:
            - main
      paths:
        include:
          - src/*

variables:
- name: backend_app_dir
  value: 'app/sd4780_msa/src/backend'
- name: frontend_app_dir
  value: 'app/sd4780_msa/src/frontend'

parameters:
- name: cleanNpmCache
  type: boolean
  default: false

jobs:
- job: Job
  pool:
    name: 'Azure Pipelines'
  steps:
  - task: Bash@3
    displayName: 'Clone projects with scripts'
    inputs:
      targetType: filePath
      filePath: ./build/gitClone.sh

  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '16.x'

  - ${{ if eq(parameters.cleanNpmCache, true) }}:
    - task: CmdLine@2
      displayName: 'BE - npm clean cache'
      inputs:
        script: |
          npm cache clean --force
          npm cache verify
        workingDirectory: $(backend_app_dir)

  - template: templates/app-npm-build.yml
    parameters:
      appDir: $(backend_app_dir)
      appName: BE App

  - task: Docker@1
    displayName: 'Build an image BE'
    inputs:
      azureSubscriptionEndpoint: 'Azure ACR Subscription (015efe71-65eb-4453-a4b3-ba0b62119434)'
      azureContainerRegistry: tuanphama3containerregistry.azurecr.io
      command: Build an image
      dockerFile: $(backend_app_dir)/Dockerfile
      buildContext: '**'
      imageName:  'acr-tuanphama3-devops-backend'

  - task: Docker@1
    displayName: 'Push an image BE'
    inputs:
      azureSubscriptionEndpoint: 'Azure ACR Subscription (015efe71-65eb-4453-a4b3-ba0b62119434)'
      azureContainerRegistry: tuanphama3containerregistry.azurecr.io
      command: Push an image
      buildContext: '**'
      imageName:  'acr-tuanphama3-devops-backend'

  - ${{ if eq(parameters.cleanNpmCache, true) }}:
    - task: CmdLine@2
      displayName: 'FE - npm clean cache'
      inputs:
        script: |
          npm cache clean --force
          npm cache verify
        workingDirectory: $(frontend_app_dir)

  - template: templates/app-npm-build.yml
    parameters:
      appDir: $(frontend_app_dir)
      appName: FE App

  - task: Docker@1
    displayName: 'Build an image FE'
    inputs:
      azureSubscriptionEndpoint: 'Azure ACR Subscription (015efe71-65eb-4453-a4b3-ba0b62119434)'
      azureContainerRegistry: tuanphama3containerregistry.azurecr.io
      command: Build an image
      dockerFile: $(frontend_app_dir)/Dockerfile
      buildContext: '**'
      imageName:  'acr-tuanphama3-devops-frontend'

  - task: Docker@1
    displayName: 'Push an image FE'
    inputs:
      azureSubscriptionEndpoint: 'Azure ACR Subscription (015efe71-65eb-4453-a4b3-ba0b62119434)'
      azureContainerRegistry: tuanphama3containerregistry.azurecr.io
      command: Push an image
      buildContext: '**'
      imageName:  'acr-tuanphama3-devops-frontend'
