pool:
  vmImage: 'ubuntu-latest'

name: $(Build.BuildId)

trigger:
  branches:
    include:
    - main

variables:
- name: frontend_app_dir
  value: 'src/frontend-app'

parameters:
- name: cleanNpmCache
  type: boolean
  default: false

steps:
  - script: |
      echo "Hello Azure Devops"